server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/DHMax

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
management:
  endpoints:
    web:
      exposure:
        include: ´*´
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      catalog:
        slidingWindowType: COUNT_Based
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFails: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      catalog:
        waitDuration: 1000
        maxAttempts: 3
        #retryExceptions:
          #- feign.FeignException$InternalServerError

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Microservice For DHMax
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
