server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/DHMax
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true 
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue
  

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_Based
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFails: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
      series:
        slidingWindowType: COUNT_Based
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFails: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      movies:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
      series:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Microservice For DHMax
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
