server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          #uri: lb://movie-service
          uri: http://localhost:8083
          predicates:
            - Path=/movies/**
        - id: serie-service
          #uri: lb://serie-service
          uri: http://localhost:8098
          predicates:
            - Path=/series/**
        - id: catalog-service
          #uri: lb://catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/catalog/**
          filters:           
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddRequestHeader=user-request-header, custom-user-request-header
        - AddResponseHeader=user-response-header, custom-user-response-header
        - LogFilter=Checkpoint I de Backend II, by Antonela Dutruel
        #- TokenRelay
  #security:
    #oauth2:
      #client:
        #registration:
          #github:
            #client-id: 5f4f18a5a0c0790bba75
            #client-secret: 0855bf0b915e3c9a0757c06efbf1fa7fcff6ef36

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
