server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          #uri: lb://movie-service
          uri: http://localhost:8083
          predicates:
            - Path=/movie-service/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
            - LogFilter=Checkpoint I de Backend II, by Antonela Dutruel
        - id: catalog-service
          #uri: lb://catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/catalog-service/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
            - LogFilter=Checkpoint I de Backend II, by Antonela Dutruel
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true