server:
    port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
  
  sql:
    init:
      dataLocations: classpath:/movie-service.sql  
      
  jpa: 
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
