server:
  port : 8087
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/DHMax
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
