server:
  port : 8087
  
spring:
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/DHMax
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  serie:
    name: serieQueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
